[build]
  command = "npm run build"     # atau "yarn build"
  publish = "dist"              # Vite output folder defaultnya "dist"
  functions = "netlify/functions"  # kalau pakai serverless functions

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200